# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Infectious Waste
tagline:          'wants to infect you'
description:      'Are you infected yet?'
url:              http://infectiouswaste.github.io
baseurl:          /

author:
  name:           'Infectious Waste'
  url:            https://infectiouswaste.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/infectiouswaste
